id: IB1BEB07B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T19:59:40+00:00'
last_modified: '2022-06-07T16:09:01.026546+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25065
  title: རྗེ་ཙོང་ཁ་པ་ཡབ་སྲས་ཀྱིས་མཛད་པའི་ལྟ་བའི་གསུང་རྩོམ་ཕྱོགས་བསྡུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A09E:
      image_group_id: I1KG25067
      title: ''
      total_pages: 530
      order: 1
      base_file: A09E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
